<table border="1" padding="1" spacing="0">
<tr>  <td><tt>d</tt></td>  <td>the day as number without a leading zero (1 to 31)</td>  </tr>
<tr>  <td><tt>dd</tt></td>  <td>the day as number with a leading zero (01 to 31)</td>  </tr>
<tr>  <td><tt>ddd</tt></td>  <td>the abbreviated localized day name (e.g. 'Mon' to 'Sun').</td>  </tr>
<tr>  <td><tt>dddd</tt></td>  <td>the long localized day name (e.g. 'Monday' to 'Sunday').</td>  </tr>
<tr>  <td><tt>M</tt></td>  <td>the month as number without a leading zero (1-12)</td>  </tr>
<tr>  <td><tt>MM</tt></td>  <td>the month as number with a leading zero (01-12)</td>  </tr>
<tr>  <td><tt>MMM</tt></td>  <td>the abbreviated localized month name (e.g. 'Jan' to 'Dec').</td>  </tr>
<tr>  <td><tt>MMMM</tt></td>  <td>the long localized month name (e.g. 'January' to 'December').</td>  </tr>
<tr>  <td><tt>yy</tt></td>  <td>the year as two digit number (00-99)</td>  </tr>
<tr>  <td><tt>yyyy</tt></td>  <td>the year as four digit number</td>  </tr>
<tr>  <td><tt>h</tt></td>  <td>the hour without a leading zero (0 to 23 or 1 to 12 if AM/PM display)</td>  </tr>
<tr>  <td><tt>hh</tt></td>  <td>the hour with a leading zero (00 to 23 or 01 to 12 if AM/PM display)</td>  </tr>
<tr>  <td><tt>H</tt></td>  <td>the hour without a leading zero (0 to 23, even with AM/PM display)</td>  </tr>
<tr>  <td><tt>HH</tt></td>  <td>the hour with a leading zero (00 to 23, even with AM/PM display)</td>  </tr>
<tr>  <td><tt>m</tt></td>  <td>the minute without a leading zero (0 to 59)</td>  </tr>
<tr>  <td><tt>mm</tt></td>  <td>the minute with a leading zero (00 to 59)</td>  </tr>
<tr>  <td><tt>s</tt></td>  <td>the second without a leading zero (0 to 59)</td>  </tr>
<tr>  <td><tt>ss</tt></td>  <td>the second with a leading zero (00 to 59)</td>  </tr>
<tr>  <td><tt>z</tt></td>  <td>the milliseconds without leading zeroes (0 to 999)</td>  </tr>
<tr>  <td><tt>zzz</tt></td>  <td>the milliseconds with leading zeroes (000 to 999)</td>  </tr>
<tr>  <td><tt>AP</tt> or <tt>A</tt></td>  <td>interpret as an AM/PM time. AP must be either "AM" or "PM".</td>  </tr>
<tr>  <td><tt>ap</tt> or <tt>a</tt></td>  <td>Interpret as an AM/PM time. ap must be either "am" or "pm".	</td>  </tr>
</table>
