<li><img src=":/lib/copy16_excel.png"> <b>Copy selection (Excel)</b>:<ul>
  <li><img src=":/lib/copy16_excel.png"> <b>Copy Selection to Clipboard (for Excel ...)</b> copies the selected cells as a table in a format, which can be pasted into Microsoft Excel (i.e. using the system settings for decinal separator)</li>
  <li><img src=":/lib/copy16_excel_nohead.png"> <b>Copy Selection to clipboard (for Excel ...) without header row/column</b> copies the selected cells as a table in a format, which can be pasted into Microsoft Excel (i.e. using the system settings for decinal separator), but omits the row/column headers</li>
</ul></li>
<li><img src=":/lib/copy16_csv.png"> <b>Copy selection (CSV)</b>:<ul>
  <li><img src=":/lib/copy16_csv.png"> <b>Copy Selection to Clipboard (CSV)</b> copies the selected cells as a table as comma-separated values ('.' as decimal separator!) </li>
  <li><img src=":/lib/copy16_csv_nohead.png"> <b>Copy Selection to clipboard (CSV) without header row/column</b> copies the selected cells as a table as comma-separated values ('.' as decimal separator!), but omits the row/column headers </li>
</ul></li>
<li><img src=":/lib/copy16_matlab.png"> <b>Copy selection (Matlab)</b>:<ul>
  <li><img src=":/lib/copy16_matlab.png"> <b>Copy Selection to clipboard (Matlab)</b> copies the selected cells as a Matlab script, which defines a matrix variable containing the data of all selected cells </li>
</ul></li>
<li><img src=":/lib/print.png"> <b>Print Table</b> prints the full table (you will be asked to specify, how the table should be fitted onto the page).</li>
<li><img src=":/lib/copy16_image.png"> <b>Copy table as image</b> copies the full current table as an image into the clipboard (e.g. to paste into a document or presentation)</li>
<li><img src=":/lib/savedata.png"> <b>save selection:</b><ul>
  <li><img src=":/lib/savedata.png"> <b>Save selection</b> saves the selected cells into a file </li>
  <li><img src=":/lib/savedata_flipped.png"> <b>Save selection, flipped</b> saves the selected cells into a file and rotates the table</li>
  <li><img src=":/lib/savedata.png"> <b>Save selection, extended form</b> saves the selected cells in expanded form (i.e. every cell, whcih contains a vector/matrix is expanded into several columns) into a file</li>
  <li><img src=":/lib/savedata_flipped.png"> <b>Save selection, extended form, flipped</b> saves the selected cells in expanded form (i.e. every cell, which contains a vector/matrix is expanded into several rows) into a file and rotates the table. </li>
</ul></li> 
