INCLUDEPATH += xlslib-package-2.4.0/xlslib/xlslib/src/

HEADERS += xlslib-package-2.4.0/xlslib/xlslib/src/xlslib.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/common/xlsys.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/common/xlstypes.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/common/xls_pshpack4.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/common/xls_pshpack2.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/common/xls_pshpack1.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/common/xls_poppack.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/common/timespan.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/common/systype.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/common/stringtok.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/common/overnew.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/oledoc/oleprop.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/oledoc/olefs.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/oledoc/oledoc.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/oledoc/binfile.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/workbook.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/unit.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/tostr.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/summinfo.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/sheetrec.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/row.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/rectypes.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/record.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/recdef.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/range.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/number.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/note.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/merged.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/label.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/index.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/HPSF.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/globalrec.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/formula_expr.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/formula_estimate.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/formula_const.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/formula_cell.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/formula.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/formtags.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/format.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/font.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/extformat.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/err.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/docsumminfo.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/datast.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/continue.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/common.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/colors.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/colinfo.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/cell.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/cbridge.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/boolean.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/blank.h \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/biffsection.h

SOURCES +=  xlslib-package-2.4.0/xlslib/xlslib/src/common/overnew.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/oledoc/oleprop.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/oledoc/olefs.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/oledoc/oledoc.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/oledoc/binfile.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/workbook.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/unit.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/summinfo.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/sheetrec.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/row.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/record.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/recdef.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/range.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/number.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/note.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/merged.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/label.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/index.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/HPSF.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/globalrec.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/formula_expr.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/formula_estimate.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/formula_cell.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/formula.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/format.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/font.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/extformat.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/err.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/docsumminfo.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/datast.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/continue.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/colors.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/colinfo.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/cell.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/cbridge.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/boolean.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/blank.cpp \
    xlslib-package-2.4.0/xlslib/xlslib/src/xlslib/assert_assist.cpp

